import { Sparkles, ShieldQuestion } from "lucide-react";

export type AiReview = {
  summary: string;
  strengths: string[];
  risks: string[];
  suggestedFocus: string;
  model: string;
  generatedAt: number;
};

/**
 * Read-only AI context for a submission.
 *
 * This component is deliberately opinion-free: it renders analysis and stops.
 * It has no score, no score adjustment and no submit control, because the
 * product rule is that AI assists a human judge and never makes or alters the
 * judging decision. The disclaimer states that in the UI so a judge always
 * knows what they are looking at and who owns the call.
 */
export function AdvisoryPanel({
  review,
  audience,
}: {
  review: AiReview | null | undefined;
  /** Framed for whoever is reading, so a judge and a participant each get the
   *  framing that is accurate for them. */
  audience: "judge" | "participant";
}) {
  if (!review) return null;

  return (
    <section className="surface-card overflow-hidden">
      <header className="flex items-center justify-between gap-3 border-b border-border bg-info-soft px-4 py-2.5">
        <span className="flex items-center gap-2 text-xs font-semibold text-info-foreground">
          <Sparkles className="size-3.5" />
          AI briefing
        </span>
        <span className="rounded-full bg-card px-2 py-0.5 text-[0.6875rem] font-semibold text-muted-foreground">
          Advisory only
        </span>
      </header>

      <div className="p-4">
        <p className="flex items-start gap-2.5 rounded-md border border-warning/30 bg-warning-soft px-3 py-2.5 text-xs leading-relaxed text-warning-foreground">
          <ShieldQuestion className="mt-px size-4 shrink-0" />
          <span>
            {audience === "judge"
              ? "Machine-generated context to speed up your read. It carries no score and cannot change one — the scorecard is entirely yours."
              : "This is the machine-generated briefing judges also see. It has no effect on your score, and no judge is required to follow it."}
          </span>
        </p>

        <p className="mt-4 text-sm leading-relaxed text-foreground">{review.summary}</p>

        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          <div className="surface-inset p-3">
            <p className="text-xs font-semibold text-success-foreground">
              Noted strengths
            </p>
            <ul className="mt-2 space-y-1.5">
              {review.strengths.map((item) => (
                <li
                  key={item}
                  className="flex gap-2 text-xs leading-relaxed text-muted-foreground"
                >
                  <span aria-hidden className="font-semibold text-success">
                    +
                  </span>
                  {item}
                </li>
              ))}
            </ul>
          </div>

          <div className="surface-inset p-3">
            <p className="text-xs font-semibold text-danger-foreground">
              Gaps worth probing
            </p>
            <ul className="mt-2 space-y-1.5">
              {review.risks.map((item) => (
                <li
                  key={item}
                  className="flex gap-2 text-xs leading-relaxed text-muted-foreground"
                >
                  <span aria-hidden className="font-semibold text-destructive">
                    !
                  </span>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="mt-3 rounded-md border border-border bg-card p-3">
          <p className="text-xs font-semibold">
            Suggested question to ask the team
          </p>
          <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
            {review.suggestedFocus}
          </p>
        </div>

        <p className="mt-3 text-[0.6875rem] text-muted-foreground">
          Generated by {review.model}
        </p>
      </div>
    </section>
  );
}
